version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # Uncomment extra hosts below if you are using Linux OS, on OSX and Windows it should work OOTB
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
